lendahand/src/main/java/au/group/events/model/Event.java
package au.group.events.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

import au.group.stats.model.Karma;
import au.group.users.model.User;

@Entity
@Table(name = "events", catalog = "lendahand")
public class Event {

	private int id;
	private String name;
	private Date dateCreated;
	private Date startDate;
	private Date endDate;
	private String description;
	private String loc;
	private User createdBy;
	private int maxVolunteers;
	private float lat;
	private float lng;
	
	//private List<User> currVolunteers;
	private Set<User> pledgedUsers = new HashSet<User>();
	private Set<Karma> awardedUsers;
	private boolean isAwardingFinished;
	
	public Event(){
	}
	
	public Event(String name, String description, String loc, User createdBy, int maxVolunteers,Date startDate) {
		this.name = name;
		this.dateCreated = new Date();
		this.startDate = startDate;
		this.description = description;
		this.loc = loc;
		this.createdBy = createdBy;
		this.maxVolunteers = maxVolunteers;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="id", unique = true)
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name="loc")
	@Type(type="string")
	public String getLoc() {
		return loc;
	}
	public void setLoc(String loc) {
		this.loc = loc;
	}
	
	@Column(name="dateCreated")
	@Type(type="date")
	public Date getDateCreated() {
		return dateCreated;
	}
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	public void setDateCreatedToNow(){
		this.dateCreated = new Date();
	}
	
	@Column(name="startDate")
	@Type(type="date")
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	
	@Column(name="description")
	@Type(type="string")
	public String getDesc() {
		return description;
	}
	public void setDesc(String desc) {
		this.description = desc;
	}
	
	@Column(name="name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public User getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name="maxVolunteers")
	@Type(type="integer")
	public int getMaxVolunteers() {
		return maxVolunteers;
	}
	public void setMaxVolunteers(int maxVolunteers) {
		this.maxVolunteers = maxVolunteers;
	}

	@Column(name="lat")
	@Type(type="float")
	public void setLat(float lat){
		this.lat = lat;
	}
	public float getLat(){
		return this.lat;
	}
	@Column(name="lng")
	@Type(type="float")
	public void setLng(float lng){
		this.lng = lng;
	}
	public float getLng(){
		return this.lng;
	}
	/*
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = true)
	public List<User> getCurrVolunteers() {
		return currVolunteers;
	*/

	/* DEANS ADDITIONS */
	@ManyToMany(cascade = {CascadeType.ALL}, fetch=FetchType.EAGER)
    @JoinTable(name="event_pledges", 
                joinColumns={@JoinColumn(name="event_id")}, 
                inverseJoinColumns={@JoinColumn(name="user_id")})
	public Set<User> getPledgedUsers() {
		return pledgedUsers;
	}

	public void setPledgedUsers(Set<User> pledgedUsers) {
		this.pledgedUsers = pledgedUsers;
	}
	
	
	public void addPledger(User pledger){
		this.pledgedUsers.add(pledger);
	}
	
	public void removePledger(User pledger){
		this.pledgedUsers.remove(pledger);
	}
	
	@OneToMany(mappedBy="event", fetch=FetchType.EAGER)
	public Set<Karma> getAwardedUsers() {
		return awardedUsers;
	}

	public void setAwardedUsers(Set<Karma> awardedUsers) {
		this.awardedUsers = awardedUsers;
	}
	
	@Column(name = "awarding_finished")
	@Type(type="boolean")
	public boolean isAwardingFinished() {
		return isAwardingFinished;
	}

	/**
	 * @return the endDate
	 */
	@Column(name="endDate")
	@Type(type="date")
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * @param endDate the endDate to set
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setAwardingFinished(boolean isAwardingFinished) {
		this.isAwardingFinished = isAwardingFinished;

	}
}

lendahand/src/main/java/au/group/web/controller/EventController.java
package au.group.web.controller;

import java.util.Collections;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import au.group.events.model.Event;
import au.group.events.service.EventService;
import au.group.locations.service.MyLocationsService;
import au.group.stats.model.Stat;
import au.group.stats.service.StatsService;
import au.group.tools.DateComparer;
import au.group.users.model.User;
import au.group.users.service.UserService;

@Controller
@RequestMapping(value = "/events/**")
public class EventController {

	@Autowired
	private EventService eventService;
	@Autowired
	private UserService userService;
	@Autowired
	private MyLocationsService locationService;
	@Autowired
	private StatsService statsService;

	// CREATE Event
	@RequestMapping(value = "/createevent", method = RequestMethod.GET)
	public ModelAndView createEventPage(HttpServletRequest request) {

		ModelAndView model = new ModelAndView();
		model.setViewName("events/createevent");

		return model;

	}

	// READ List of Events
	@RequestMapping(value = "/eventlist", method = RequestMethod.GET)
	public String eventListPage(Model model) {
		List<Event> events = eventService.listOfEvents();
		Collections.sort(events, new DateComparer());
		model.addAttribute("eventList", events);

		return "/events/eventlist";
	}

	// UPDATE Event Details
	@RequestMapping(value = "/update/{eventId}", method = RequestMethod.GET)
	public ModelAndView updateEvent(@PathVariable("eventId") int eventId,HttpServletRequest request) {

		ModelAndView model = new ModelAndView();
		model.setViewName("events/update/{eventId}");
		Event updatingEvent = eventService.findEventById(eventId);
		model.addObject("updateEvent", updatingEvent);

		return model;

	}

	// UPDATE Event Details
	@RequestMapping(value = "/update/{eventId}/process", method = RequestMethod.POST)
	public String updateEventProcess(@PathVariable("eventId") int eventId,
			HttpServletRequest request) {

		String name = request.getParameter("name").toString();
		String location = request.getParameter("location").toString();
		String desc = request.getParameter("desc").toString();

		eventService.updateEvent(eventId, name, location, desc);

		return "redirect:../events/eventlist";
	}

	// DELETE Event
	@RequestMapping(value = "/delete/{eventId}")
	public String deleteEvent(@PathVariable("eventId") int eventId) {

		eventService.deleteEvent(eventId);

		return "redirect:../events/eventlist";
	}

	// JOIN Event
	@RequestMapping(value = "/join/{eventId}")
	public String joinEvent(@PathVariable("eventId") int eventId) {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		User pledger = userService.getUser(auth.getName());
		locationService.joinEvent(eventId, pledger);
		String url = "redirect:../events/event/".concat(Integer.toString(eventId));

		return url;
	}
	
	// LEAVE Event
	@RequestMapping(value = "/leave/{eventId}")
	public String leaveEvent(@PathVariable("eventId") int eventId) {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		User pledger = userService.getUser(auth.getName());
		System.out.println("FLAG");
		eventService.leaveEvent(eventId, pledger);

		return "redirect:../events/eventlist";
	}
	
	// Show Event
	@RequestMapping(value = "/event/{eventId}", method = RequestMethod.GET)
	public String displayEvent(@PathVariable("eventId") int eventId, Model model) {
		model.addAttribute("event", eventService.findEventById(eventId));
		
		User host = eventService.findEventById(eventId).getCreatedBy();
		
		Stat stat = statsService.findByUsername(host.getUsername());
		
		if (stat != null)
		{
			model.addAttribute("host", host);
			model.addAttribute("score", statsService.getTotalKarma(stat));
			model.addAttribute("scoreRecent", statsService.getRecentKarma(stat));
		}
		
		return "/events/event";
	}

}

lendahand/src/main/webapp/WEB-INF/pages/events/event.jsp
<!DOCTYPE html>
<%@taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>LendAHand || ${pageContext.request.userPrincipal.name}</title>


<link href='<c:url value="/resources/css/foundation.css" />'
	rel="stylesheet">
<link href="<c:url value="/resources/css/locations.css" />"
	rel="stylesheet">
<link href="<c:url value="/resources/css/events.css" />"
	rel="stylesheet">
<link href="<c:url value="/resources/css/stats.css" />"
rel="stylesheet">
<link href='<c:url value="/resources/js/foundation.min.js" />'>
<link href='<c:url value="/resources/js/jquery.js" />'>
<script type="text/javascript"
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgexu0xK6ikbhRlkNLeIwdT1b4jiQ7Je0">
	
</script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
	var username = "<c:out value="${pageContext.request.userPrincipal.name}" />";
	var model = []
	var event = [];
	console.log("<c:out value="${event.lat}" />");
	event.lat = "<c:out value="${event.lat}" />";
	event.lng = "<c:out value="${event.lng}" />";
	event.name = "<c:out value="${event.name}" />";
	event.createdBy = "<c:out value="${event.createdBy.username}"/>";
	model.push(event);
	console.log(event.lat);
</script>
<script src="../../resources/js/eventMap.js"></script>
<link href="<c:url value="/resources/js/eventMap.js" />">
</head>

<body>
	<!-- Top navigation bar -->
	<jsp:include page="../topNav.jsp" />



	<div class='hostbox-container'>
		<div class='hostbox'>
			<h3>Host: ${event.createdBy.username}</h3>
			<!-- User Profile Picture -->
			<c:choose>
				<c:when
					test="${event.createdBy.getProfileLink() == null || event.createdBy.getProfileLink() == ''}">
					<img src="http://placehold.it/200x150&text=No+Profile+Picture+Set">
				</c:when>
				<c:otherwise>
					<img src="http://${event.createdBy.getProfileLink()}"
						style="width: 200px; height: 150px">
				</c:otherwise>
			</c:choose>
			
			<div class="smallcontainer">
				<div class="icon">
					<img src="<c:url value="/resources/img/eternal_glyph.png"/>"
						class="symbol" />
				</div>
	
				<div class="score">
					<c:out value="${score}" />
				</div>
			</div>

			<div class="smallcontainer">
				<div class="icon">
					<img src="<c:url value="/resources/img/transient_glyph.png"/>"
						class="symbol" />
				</div>
				<div class="score">
					<c:out value="${scoreRecent}"/>
				</div>
			</div>
		</div>
	</div>

	<div class='contentbox'>
		<h1>${event.name}</h1>
		<p>${event.desc}</p>

		<div class="float-canvas">
			<div id="map-canvas"></div>
		</div>

		<br>

		<div class='column'>
			<div class='userlist'>
				<h3>Users Attending</h3>
				<table>
					<c:forEach items="${event.pledgedUsers}" var="user">
						<tr>
							<td>${user.getUsername()}</td>
						</tr>
					</c:forEach>
				</table>
			</div>

			<div class='share'>
				<form action="<c:url value='../../social/post/event'/>" method="POST">
					<input name="message" type="text" placeholder="Tell your friends something about this cause...">
					<input name="submit" type="submit" class="button">
					<input type=hidden name="id" value="<c:out value="${event.id}"/>" >
					<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
				</form>
			</div>

			<br>

			<div class='action-button'>
				<c:choose>
					<c:when
						test="${event.createdBy.getUsername()==pageContext.request.userPrincipal.name}">
						<c:if test="${event.awardingFinished==false}">
							<a class='butt'
								href="${pageContext.request.contextPath}/events/${event.id}/award">Give
								Karma </a>
							<br>
							<br>
							<a class='buttonLeave'
								href="${pageContext.request.contextPath}/events/delete/${event.id}">Delete
								Event</a>
						</c:if>
					</c:when>

					<c:otherwise>

						<c:set var="contains" value="false" />
						<c:forEach var="item" items="${event.pledgedUsers}">
							<c:if
								test="${item.getUsername() eq pageContext.request.userPrincipal.name}">
								<c:set var="contains" value="true" />
							</c:if>
						</c:forEach>

						<c:if test="${event.awardingFinished==false}">
							<c:choose>
								<c:when test="${contains==true}">
									<!-- <a class='buttonLeave'
										href="${pageContext.request.contextPath}/events/leave/${event.id}">Leave</a> -->
								</c:when>

								<c:otherwise>
									<a class='butt'
										href="${pageContext.request.contextPath}/events/join/${event.id}">Join</a>
								</c:otherwise>
							</c:choose>
						</c:if>
					</c:otherwise>
				</c:choose>
			</div>

		</div>
	</div>
</body>
</html>

lendahand/src/main/webapp/WEB-INF/pages/events/eventlist.jsp
<!DOCTYPE html>
<%@taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>LendAHand || ${pageContext.request.userPrincipal.name}</title>


<link href='<c:url value="/resources/css/foundation.css" />'
	rel="stylesheet">
<link href='<c:url value="/resources/js/foundation.min.js" />'>
<link href="<c:url value="/resources/css/events.css" />"	rel="stylesheet">
<link href='<c:url value="/resources/js/jquery.js" />'>
</head>

<body>
	<!-- Top navigation bar -->
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1>
					<a href="${pageContext.request.contextPath}/">LendAHand</a>
				</h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->

			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>

		<section class="top-bar-section">
			<!-- Right Nav Section | Includes log out button-->
			<ul class="right">
				<li class="active"><sec:authorize access="hasRole('ROLE_USER')">
						<c:url value="/logout" var="logoutUrl" />
						<form action="${logoutUrl}" method="post" id="logoutForm">
							<input type="hidden" name="${_csrf.parameterName}"
								value="${_csrf.token}" />
						</form>
						<script>
							function formSubmit() {
								document.getElementById("logoutForm").submit();
							}
						</script>



						<a href="javascript:formSubmit()">Log Off</a>
					</sec:authorize></li>


			</ul>

			<!-- Left Nav Section -->
			<ul class="left">
				<li><a href=${pageContext.request.contextPath}/profile>Profile</a></li>
				<li><a href=${pageContext.request.contextPath}/events/eventlist>Causes</a></li>
				<li><a href=${pageContext.request.contextPath}/stats>Stats</a></li>
				<li><a href=${pageContext.request.contextPath}/connect/facebook>Social</a></li>
				<li><a href=${pageContext.request.contextPath}/map>Map</a></li>
			</ul>
		</section>
	</nav>

	<table class="contentlist">
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Location</th>
			<th>Max Number of Volunteers</th>
			<th>Date</th>
			<th>Host</th>
			<th>Action</th>
		</tr>
		<c:forEach items="${eventList}" var="event">
			<tr>
				<td><a href="${pageContext.request.contextPath}/events/event/${event.id}">${event.name}</a></td>
				<td>${event.desc}</td>
				<td>${event.loc}</td>
				<td>${event.maxVolunteers}</td>
				<td>${event.startDate}</td>
				<td>${event.createdBy.getUsername()}</td>
				<td><c:choose>
						<c:when
							test="${event.createdBy.getUsername()==pageContext.request.userPrincipal.name}">
							<c:if test="${event.awardingFinished==false}">
									<a href="${pageContext.request.contextPath}/events/${event.id}/award">Give Karma</a>
									<br>
									<a href="${pageContext.request.contextPath}/events/delete/${event.id}">Delete</a>
							</c:if>	
						</c:when>

						<c:otherwise>
						
							<c:set var="contains" value="false" />
							<c:forEach var="item" items="${event.pledgedUsers}">
								<c:if test="${item.getUsername() eq pageContext.request.userPrincipal.name}">
									<c:set var="contains" value="true" />
								</c:if>
							</c:forEach>
							
							<c:if test="${event.awardingFinished==false}">
								<c:choose>
									<c:when test="${contains==true}">
										<!--<a href="${pageContext.request.contextPath}/events/leave/${event.id}">Leave</a> -->
									</c:when>
									
									<c:otherwise>
										<a href="${pageContext.request.contextPath}/events/join/${event.id}">Join</a>
									</c:otherwise>
								</c:choose>
							</c:if>
						</c:otherwise>
					</c:choose></td>
			</tr>
		</c:forEach>
	</table>

	<br>

	<a class='centre-butt' href="${pageContext.request.contextPath}/map">List
		A New Cause</a>

</body>
</html>

lendahand/src/main/webapp/WEB-INF/pages/events/update.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page session="true"%>
<html>
<head>
<title>LendAHand || Create Event</title>

<link href="<c:url value="/resources/css/foundation.css" />"
	rel="stylesheet">
<link href="<c:url value="/resources/css/foundation.min.css" />"
	rel="stylesheet">
</head>
<body onload='document.newEventForm.name.focus();'>


	<div align="center">


		<h1>Let's Start Giving Back, Have Some Fun...</h1>
		<h1>
			<strong><i>And Feel Great.</i></strong>
		</h1>
		<br>
	</div>
	<div align="center"
		style="margin-left: auto; margin-right: auto; width: 50%;">
		<h3>Create New Event!</h3>



		<form action="<c:url value='events/update/{eventId}/process'" method="post" commandname="updateEvent" id="updateForm">
							<input type="hidden" name="${_csrf.parameterName}"
								value="${_csrf.token}" />
			<table>
				<tr>
					<td>Event name:</td>
					<td><input path="name" type='text' name='name'></td>
				</tr>
				<tr>
					<td>Location:</td>
					<td><input  path="loc" type='text' name='location' /></td>
				</tr>
				<tr>
					<td>Description:</td>
					<td><input  path="description" type='text' name='desc' /></td>
				</tr>
			</table>
		</form>
	</div>

</body>
</html>